### ISSUE TITLE
RegisterEnrollmentView TODO

### ISSUE THREAD

**Issue by skarlatosstratos** [SimPlat/Athina#10]
- [x] Use checkbox label text instead of extra labels

- [x] setEnable(), function to enable/disable  desired lectures

- [x] function to upload to DB the selected checkboxes
